export const NOME_ARQUIVO_EXEMPLO = 'exemplo-curso-com-marcadores.docx'

export const LINHAS_DOCUMENTO_EXEMPLO: string[] = [
  'CURSO: Introdução à Segurança do Trabalho',
  'DESCRIÇÃO: Fundamentos da segurança do trabalho, da legislação básica à identificação e ao controle de riscos no ambiente laboral. Voltado para trabalhadores e supervisores de todos os setores.',
  'CARGA HORÁRIA: 8 horas',
  'MODALIDADE: Online',
  'CATEGORIA: Gestão',
  '',

  'UNIDADE 1: Legislação e Normas Regulamentadoras',
  '',
  'OBJETIVOS_INICIO',
  'Objetivo: Identificar a base legal da segurança do trabalho no Brasil',
  'Objetivo: Reconhecer as Normas Regulamentadoras aplicáveis à sua atividade',
  'OBJETIVOS_FIM',
  '',
  'A segurança do trabalho no Brasil é regulamentada por um conjunto de leis e normas que visam proteger o trabalhador de acidentes e doenças ocupacionais. A principal base legal é a Consolidação das Leis do Trabalho (CLT), que determina a obrigatoriedade de medidas de proteção à saúde e à integridade física dos trabalhadores.',
  '',
  'As Normas Regulamentadoras (NRs) são criadas pelo Ministério do Trabalho e estabelecem os requisitos técnicos e legais para garantir a segurança nos ambientes de trabalho.',
  '',
  'LISTA_INICIO',
  'Tipo: nao-ordenada',
  'Item: NR-1: Disposições Gerais e Gerenciamento de Riscos Ocupacionais',
  'Item: NR-5: Comissão Interna de Prevenção de Acidentes (CIPA)',
  'Item: NR-6: Equipamentos de Proteção Individual (EPI)',
  'Item: NR-12: Segurança no Trabalho em Máquinas e Equipamentos',
  'LISTA_FIM',
  '',
  'INFOBOX_INICIO',
  'Tipo: atencao',
  'Título: Descumprimento das NRs',
  'Conteúdo: O descumprimento das Normas Regulamentadoras sujeita a empresa a multas, interdição do estabelecimento e responsabilização civil e criminal em caso de acidente.',
  'INFOBOX_FIM',
  '',
  'TIMELINE_INICIO',
  'Orientação: vertical',
  'Data: 1943',
  'Título do Evento: Criação da CLT',
  'Descrição do Evento: A Consolidação das Leis do Trabalho estabelece o primeiro marco legal de proteção à saúde do trabalhador no Brasil.',
  'Data: 1978',
  'Título do Evento: Publicação das primeiras NRs',
  'Descrição do Evento: A Portaria 3.214 institui as Normas Regulamentadoras, detalhando obrigações técnicas de segurança e medicina do trabalho.',
  'Data: 2022',
  'Título do Evento: Nova redação da NR-1',
  'Descrição do Evento: O Gerenciamento de Riscos Ocupacionais passa a ser exigência central, com o PGR substituindo o antigo PPRA.',
  'TIMELINE_FIM',
  '',
  'SEPARADOR_INICIO',
  'Estilo: linha',
  'SEPARADOR_FIM',
  '',
  'TABS_INICIO',
  'Título da Aba 1: Responsabilidade do empregador',
  'Conteúdo da Aba 1: Fornecer ambiente seguro, elaborar o PGR, custear os EPIs e treinar os trabalhadores sobre os riscos da atividade.',
  'Título da Aba 2: Responsabilidade do trabalhador',
  'Conteúdo da Aba 2: Usar o EPI fornecido, cumprir os procedimentos de segurança e comunicar ao superior qualquer condição de risco identificada.',
  'Título da Aba 3: Papel da CIPA',
  'Conteúdo da Aba 3: Identificar riscos, elaborar o Mapa de Riscos, investigar acidentes e promover a Semana Interna de Prevenção de Acidentes.',
  'TABS_FIM',
  '',

  'UNIDADE 2: Identificação e Classificação de Riscos',
  '',
  'Risco ocupacional é qualquer condição do ambiente de trabalho capaz de causar dano à saúde do trabalhador. A identificação sistemática desses riscos é o primeiro passo de qualquer programa de prevenção.',
  '',
  'ACCORDION_INICIO',
  'Título do Item 1: Riscos físicos',
  'Conteúdo do Item 1: Ruído, vibração, temperaturas extremas, radiações e pressões anormais. São agentes que se propagam pelo ambiente e atingem o trabalhador à distância.',
  'Título do Item 2: Riscos químicos',
  'Conteúdo do Item 2: Poeiras, fumos, névoas, gases e vapores que podem ser absorvidos por via respiratória, cutânea ou digestiva.',
  'Título do Item 3: Riscos biológicos',
  'Conteúdo do Item 3: Vírus, bactérias, fungos e parasitas presentes em atividades de saúde, saneamento e manipulação de alimentos.',
  'Título do Item 4: Riscos ergonômicos',
  'Conteúdo do Item 4: Esforço físico intenso, postura inadequada, repetitividade e jornada prolongada.',
  'ACCORDION_FIM',
  '',
  'FLIPCARD_INICIO',
  'Frente do Card 1: O que é o Mapa de Riscos?',
  'Verso do Card 1: Representação gráfica dos riscos existentes em cada setor da empresa, elaborada pela CIPA com participação dos trabalhadores e afixada em local visível.',
  'Frente do Card 2: Quem elabora o Mapa de Riscos?',
  'Verso do Card 2: A CIPA, com a participação dos trabalhadores de todos os setores e assessoria do SESMT, quando houver.',
  'Frente do Card 3: Onde o Mapa de Riscos deve ficar?',
  'Verso do Card 3: Afixado em local visível e de fácil acesso no próprio setor mapeado, para consulta de todos os trabalhadores.',
  'FLIPCARD_FIM',
  '',
  'IMAGEM_INICIO',
  'URL: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Safety_helmet.jpg/640px-Safety_helmet.jpg',
  'Legenda: Capacete de segurança com jugular, item obrigatório em obras',
  'Fonte: Wikimedia Commons',
  'Tamanho: media',
  'IMAGEM_FIM',
  '',
  'HOTSPOT_INICIO',
  'URL: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Safety_helmet.jpg/640px-Safety_helmet.jpg',
  'Legenda: Partes do capacete de segurança',
  'X do Ponto 1: 50',
  'Y do Ponto 1: 20',
  'Título do Ponto 1: Casco',
  'Conteúdo do Ponto 1: Camada externa rígida que absorve e distribui o impacto. Deve ser substituída ao apresentar trincas, deformação ou perda de brilho.',
  'X do Ponto 2: 30',
  'Y do Ponto 2: 70',
  'Título do Ponto 2: Jugular',
  'Conteúdo do Ponto 2: Tira que prende o capacete ao queixo. Obrigatória em trabalho em altura e sempre que houver risco de queda do equipamento.',
  'HOTSPOT_FIM',
  '',
  'VIDEO_INICIO',
  'URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'Título: Como elaborar o Mapa de Riscos do seu setor',
  'VIDEO_FIM',
  '',

  'UNIDADE 3: Equipamentos de Proteção',
  '',
  'O Equipamento de Proteção Individual é todo dispositivo de uso individual destinado à proteção contra riscos capazes de ameaçar a segurança e a saúde no trabalho. Ele é a última barreira da hierarquia de controle: só entra quando eliminar o risco na fonte não é viável.',
  '',
  'LISTA_INICIO',
  'Tipo: ordenada',
  'Item: Eliminar o risco na fonte',
  'Item: Substituir o agente ou o processo por um menos perigoso',
  'Item: Adotar medidas de proteção coletiva',
  'Item: Adotar medidas administrativas e de organização do trabalho',
  'Item: Fornecer o Equipamento de Proteção Individual adequado',
  'LISTA_FIM',
  '',
  'INFOBOX_INICIO',
  'Tipo: saiba_mais',
  'Título: Certificado de Aprovação',
  'Conteúdo: Ao selecionar um EPI, verifique sempre o Certificado de Aprovação (CA) emitido pelo Ministério do Trabalho. EPIs sem CA não são aprovados para uso profissional.',
  'INFOBOX_FIM',
  '',
  'CARROSSEL_INICIO',
  'Exibição: carrossel',
  'URL da Imagem 1: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Safety_helmet.jpg/640px-Safety_helmet.jpg',
  'Legenda da Imagem 1: Capacete de segurança classe B',
  'Fonte da Imagem 1: Wikimedia Commons',
  'URL da Imagem 2: https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Safety_glasses.jpg/640px-Safety_glasses.jpg',
  'Legenda da Imagem 2: Óculos de proteção contra impactos',
  'Fonte da Imagem 2: Wikimedia Commons',
  'CARROSSEL_FIM',
  '',
  'AUDIO_INICIO',
  'URL: https://exemplo.senai.br/audios/uso-correto-de-epi.mp3',
  'Título: Uso correto do EPI — narração da unidade',
  'Transcrição: O Equipamento de Proteção Individual só cumpre sua função quando está em bom estado, tem Certificado de Aprovação válido e é usado durante toda a exposição ao risco.',
  'AUDIO_FIM',
  '',
  'PDF_INICIO',
  'URL: https://exemplo.senai.br/documentos/ficha-de-epi.pdf',
  'Título: Ficha de controle de entrega de EPI',
  'Permitir Download: sim',
  'PDF_FIM',
  '',
  'ASSOCIACAO_INICIO',
  'Item 1: NR-6',
  'Correspondente 1: Equipamento de Proteção Individual',
  'Item 2: NR-5',
  'Correspondente 2: Comissão Interna de Prevenção de Acidentes',
  'Item 3: NR-12',
  'Correspondente 3: Segurança em máquinas e equipamentos',
  'ASSOCIACAO_FIM',
  '',
  'CATEGORIZACAO_INICIO',
  'Categoria 1: Proteção da cabeça',
  'Item 1 da Categoria 1: Capacete de segurança',
  'Item 2 da Categoria 1: Óculos de proteção',
  'Item 3 da Categoria 1: Protetor auricular',
  'Categoria 2: Proteção dos membros',
  'Item 1 da Categoria 2: Luvas de raspa',
  'Item 2 da Categoria 2: Botina com biqueira de aço',
  'Item 3 da Categoria 2: Manga de proteção',
  'CATEGORIZACAO_FIM',
  '',
  'QUIZ_INICIO',
  'Pergunta: Qual é a principal responsabilidade do empregador em relação aos EPIs?',
  'Opção A: Cobrar do trabalhador o custo do equipamento',
  'Opção B: Fornecer gratuitamente o EPI adequado ao risco e fiscalizar o uso',
  'Opção C: Deixar a critério do trabalhador usar ou não o EPI',
  'Opção D: Fornecer apenas os EPIs mais baratos disponíveis no mercado',
  'Opção E: Comprar os EPIs uma única vez e nunca substituir',
  'Resposta Correta: B',
  '',
  'Pergunta: Em qual posição da hierarquia de controle de riscos o EPI deve ser utilizado?',
  'Opção A: Primeira opção, por ser mais fácil de implementar',
  'Opção B: Segunda opção, logo após a eliminação do risco',
  'Opção C: Qualquer posição, conforme a conveniência da empresa',
  'Opção D: Última opção, quando as demais medidas são inviáveis ou insuficientes',
  'Opção E: O EPI não faz parte da hierarquia de controle de riscos',
  'Resposta Correta: D',
  'QUIZ_FIM',
]

export const TEXTO_DOCUMENTO_EXEMPLO = LINHAS_DOCUMENTO_EXEMPLO.join('\n')
