export const NOME_ARQUIVO_EXEMPLO = 'exemplo-curso-com-marcadores.docx'

export const LINHAS_DOCUMENTO_EXEMPLO: string[] = [
  'CURSO: Introdução à Segurança do Trabalho',
  'DESCRIÇÃO: Fundamentos da segurança do trabalho, da legislação básica à identificação e ao controle de riscos no ambiente laboral. Voltado para trabalhadores e supervisores de todos os setores.',
  'CARGA HORÁRIA: 8 horas',
  'MODALIDADE: Online',
  'CATEGORIA: Gestão',
  '',

  'UNIDADE 1: Legislação e Normas Regulamentadoras',
  '',
  'OBJETIVOS_INICIO',
  'Objetivo: Identificar a base legal da segurança do trabalho no Brasil',
  'Objetivo: Reconhecer as Normas Regulamentadoras aplicáveis à sua atividade',
  'OBJETIVOS_FIM',
  '',
  'A segurança do trabalho no Brasil é regulamentada por um conjunto de leis e normas que visam proteger o trabalhador de acidentes e doenças ocupacionais. A principal base legal é a Consolidação das Leis do Trabalho (CLT), que determina a obrigatoriedade de medidas de proteção à saúde e à integridade física dos trabalhadores.',
  '',
  'As Normas Regulamentadoras (NRs) são criadas pelo Ministério do Trabalho e estabelecem os requisitos técnicos e legais para garantir a segurança nos ambientes de trabalho.',
  '',
  'LISTA_INICIO',
  'Tipo: nao-ordenada',
  'Item: NR-1: Disposições Gerais e Gerenciamento de Riscos Ocupacionais',
  'Item: NR-5: Comissão Interna de Prevenção de Acidentes (CIPA)',
  'Item: NR-6: Equipamentos de Proteção Individual (EPI)',
  'Item: NR-12: Segurança no Trabalho em Máquinas e Equipamentos',
  'LISTA_FIM',
  '',
  'INFOBOX_INICIO',
  'Tipo: atencao',
  'Título: Descumprimento das NRs',
  'Conteúdo: O descumprimento das Normas Regulamentadoras sujeita a empresa a multas, interdição do estabelecimento e responsabilização civil e criminal em caso de acidente.',
  'INFOBOX_FIM',
  '',

  'UNIDADE 2: Identificação e Classificação de Riscos',
  '',
  'Risco ocupacional é qualquer condição do ambiente de trabalho capaz de causar dano à saúde do trabalhador. A identificação sistemática desses riscos é o primeiro passo de qualquer programa de prevenção.',
  '',
  'ACCORDION_INICIO',
  'Título do Item 1: Riscos físicos',
  'Conteúdo do Item 1: Ruído, vibração, temperaturas extremas, radiações e pressões anormais. São agentes que se propagam pelo ambiente e atingem o trabalhador à distância.',
  'Título do Item 2: Riscos químicos',
  'Conteúdo do Item 2: Poeiras, fumos, névoas, gases e vapores que podem ser absorvidos por via respiratória, cutânea ou digestiva.',
  'Título do Item 3: Riscos biológicos',
  'Conteúdo do Item 3: Vírus, bactérias, fungos e parasitas presentes em atividades de saúde, saneamento e manipulação de alimentos.',
  'Título do Item 4: Riscos ergonômicos',
  'Conteúdo do Item 4: Esforço físico intenso, postura inadequada, repetitividade e jornada prolongada.',
  'ACCORDION_FIM',
  '',
  'FLIPCARD_INICIO',
  'Frente: O que é o Mapa de Riscos?',
  'Verso: Representação gráfica dos riscos existentes em cada setor da empresa, elaborada pela CIPA com participação dos trabalhadores e afixada em local visível.',
  'FLIPCARD_FIM',
  '',
  'IMAGEM_INICIO',
  'URL: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Safety_helmet.jpg/640px-Safety_helmet.jpg',
  'Legenda: Capacete de segurança com jugular, item obrigatório em obras',
  'Fonte: Wikimedia Commons',
  'Tamanho: media',
  'IMAGEM_FIM',
  '',
  'VIDEO_INICIO',
  'URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'Título: Como elaborar o Mapa de Riscos do seu setor',
  'VIDEO_FIM',
  '',

  'UNIDADE 3: Equipamentos de Proteção',
  '',
  'O Equipamento de Proteção Individual é todo dispositivo de uso individual destinado à proteção contra riscos capazes de ameaçar a segurança e a saúde no trabalho. Ele é a última barreira da hierarquia de controle: só entra quando eliminar o risco na fonte não é viável.',
  '',
  'LISTA_INICIO',
  'Tipo: ordenada',
  'Item: Eliminar o risco na fonte',
  'Item: Substituir o agente ou o processo por um menos perigoso',
  'Item: Adotar medidas de proteção coletiva',
  'Item: Adotar medidas administrativas e de organização do trabalho',
  'Item: Fornecer o Equipamento de Proteção Individual adequado',
  'LISTA_FIM',
  '',
  'INFOBOX_INICIO',
  'Tipo: saiba_mais',
  'Título: Certificado de Aprovação',
  'Conteúdo: Ao selecionar um EPI, verifique sempre o Certificado de Aprovação (CA) emitido pelo Ministério do Trabalho. EPIs sem CA não são aprovados para uso profissional.',
  'INFOBOX_FIM',
  '',
  'QUIZ_INICIO',
  'Pergunta: Qual é a principal responsabilidade do empregador em relação aos EPIs?',
  'Opção A: Cobrar do trabalhador o custo do equipamento',
  'Opção B: Fornecer gratuitamente o EPI adequado ao risco e fiscalizar o uso',
  'Opção C: Deixar a critério do trabalhador usar ou não o EPI',
  'Opção D: Fornecer apenas os EPIs mais baratos disponíveis no mercado',
  'Opção E: Comprar os EPIs uma única vez e nunca substituir',
  'Resposta Correta: B',
  '',
  'Pergunta: Em qual posição da hierarquia de controle de riscos o EPI deve ser utilizado?',
  'Opção A: Primeira opção, por ser mais fácil de implementar',
  'Opção B: Segunda opção, logo após a eliminação do risco',
  'Opção C: Qualquer posição, conforme a conveniência da empresa',
  'Opção D: Última opção, quando as demais medidas são inviáveis ou insuficientes',
  'Opção E: O EPI não faz parte da hierarquia de controle de riscos',
  'Resposta Correta: D',
  'QUIZ_FIM',
]

export const TEXTO_DOCUMENTO_EXEMPLO = LINHAS_DOCUMENTO_EXEMPLO.join('\n')
