import {
  Award,
  BookOpen,
  ChefHat,
  Compass,
  Crown,
  Flag,
  Flame,
  Gem,
  GraduationCap,
  Heart,
  Leaf,
  Lightbulb,
  Medal,
  Mountain,
  Puzzle,
  Rocket,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Trophy,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { BadgeIcon } from '@/lib/trail-progress'

export const BADGE_ICON_COMPONENTS: Record<BadgeIcon, LucideIcon> = {
  award: Award,
  star: Star,
  trophy: Trophy,
  medal: Medal,
  flame: Flame,
  zap: Zap,
  target: Target,
  rocket: Rocket,
  'shield-check': ShieldCheck,
  lightbulb: Lightbulb,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  puzzle: Puzzle,
  compass: Compass,
  flag: Flag,
  heart: Heart,
  sparkles: Sparkles,
  gem: Gem,
  crown: Crown,
  'thumbs-up': ThumbsUp,
  wrench: Wrench,
  'chef-hat': ChefHat,
  leaf: Leaf,
  mountain: Mountain,
}

export const BADGE_ICON_LABELS: Record<BadgeIcon, string> = {
  award: 'Prêmio',
  star: 'Estrela',
  trophy: 'Troféu',
  medal: 'Medalha',
  flame: 'Chama',
  zap: 'Raio',
  target: 'Alvo',
  rocket: 'Foguete',
  'shield-check': 'Escudo',
  lightbulb: 'Lâmpada',
  'book-open': 'Livro',
  'graduation-cap': 'Capelo',
  puzzle: 'Quebra-cabeça',
  compass: 'Bússola',
  flag: 'Bandeira',
  heart: 'Coração',
  sparkles: 'Brilho',
  gem: 'Joia',
  crown: 'Coroa',
  'thumbs-up': 'Joinha',
  wrench: 'Chave inglesa',
  'chef-hat': 'Chapéu de chef',
  leaf: 'Folha',
  mountain: 'Montanha',
}
