export { BlockRenderer } from './BlockRenderer'
export { blockRegistry } from './registry'
export type { BlockProps } from './registry'
export { BlockThemeProvider, DEFAULT_BLOCK_THEME } from './BlockThemeProvider'
export type { BlockTheme } from './BlockThemeProvider'

export { TituloBlock } from './TituloBlock'
export { SubtituloBlock } from './SubtituloBlock'
export { ParagrafoBlock } from './ParagrafoBlock'
export { ImagemBlock, larguraMaximaImagem } from './ImagemBlock'
export { AccordionBlock } from './AccordionBlock'
export { FlipCardBlock } from './FlipCardBlock'
export { ListaBlock } from './ListaBlock'
export { QuizBlock } from './QuizBlock'
export { InfoBoxBlock } from './InfoBoxBlock'
export { VideoBlock } from './VideoBlock'
export { ObjetivosBlock } from './ObjetivosBlock'
export { SeparadorBlock } from './SeparadorBlock'
export { TabsBlock } from './TabsBlock'
export { LinhaDoTempoBlock } from './LinhaDoTempoBlock'
export { CarrosselBlock } from './CarrosselBlock'
export { AudioBlock } from './AudioBlock'
export { PdfBlock } from './PdfBlock'
export { ImagemInterativaBlock } from './ImagemInterativaBlock'
export { AssociacaoBlock } from './AssociacaoBlock'
export { CategorizacaoBlock } from './CategorizacaoBlock'
