export { BlockRenderer } from './BlockRenderer'
export { blockRegistry } from './registry'
export type { BlockProps } from './registry'
export { BlockThemeProvider, DEFAULT_BLOCK_THEME } from './BlockThemeProvider'
export type { BlockTheme } from './BlockThemeProvider'

export { HeadingBlock as TituloBlock } from './HeadingBlock'
export { SubheadingBlock as SubtituloBlock } from './SubheadingBlock'
export { ParagraphBlock as ParagrafoBlock } from './ParagraphBlock'
export { ImageBlock as ImagemBlock, maxImageWidth as larguraMaximaImagem } from './ImageBlock'
export { AccordionBlock } from './AccordionBlock'
export { FlipCardBlock } from './FlipCardBlock'
export { ListBlock as ListaBlock } from './ListBlock'
export { QuizBlock } from './QuizBlock'
export { InfoBoxBlock } from './InfoBoxBlock'
export { VideoBlock } from './VideoBlock'
export { LearningObjectivesBlock as ObjetivosBlock } from './LearningObjectivesBlock'
export { DividerBlock as SeparadorBlock } from './DividerBlock'
export { TabsBlock } from './TabsBlock'
export { TimelineBlock as LinhaDoTempoBlock } from './TimelineBlock'
export { CarouselBlock as CarrosselBlock } from './CarouselBlock'
export { AudioBlock } from './AudioBlock'
export { PdfBlock } from './PdfBlock'
export { InteractiveImageBlock as ImagemInterativaBlock } from './InteractiveImageBlock'
export { MatchingBlock as AssociacaoBlock } from './MatchingBlock'
export { CategorizationBlock as CategorizacaoBlock } from './CategorizationBlock'
export { InteractiveVideoBlock as VideoInterativoBlock } from './InteractiveVideoBlock'
